### ISSUE TITLE
persian calendar

### ISSUE THREAD

**Issue by alizelzele** [mohebifar/angular-persian#7]
having a filter that convert `milliseconds` to persian date would be awesome.

**Comment by alizelzele** [comment]
i want to help you on that, but i have no idea how to write code in coffee script

**Comment by mohebifar** [comment]
[Angular Persian Date Picker](https://github.com/AminRahimi/angular-bootstrap-persian-datepicker) does that. It provides a filter called `persianDate`.

**Comment by alizelzele** [comment]
great. missed that. thanks
