### ISSUE TITLE
how to use in orderBy

### ISSUE THREAD

**Issue by captainhamid** [mohebifar/angular-persian#8]
سلام
برای استفاده در مرتب سازی جدول بر اساس حروف فارسی
میشه از این ماژول استفاده کرد؟ اگر میشه نحوه استفاده رو یه توضیح بیدن ممنون.
همانطور که میدونید آنگولار درمرتب سازی حروف فارسی به ترتیب الفبا مشکل داره و حروف گ چ پ ژ رو آنگولار اعمال نمیکنه.

**Comment by mohebifar** [comment]
خیر همچین قابلیتی وجود نداره. اگر احساس می‌کنید که همچین فیلتری نیاز هست، خیلی خوب می‌شه اگر یه پی‌آر ایجاد کنید.

**Comment by reshadman** [comment]
@captainhamid 
ایژوها برای این نیستن که بیاین مشکل خودتون رو-- یا چیزی که وجود نداره رو-- ، از کانتریبیوتر ها بخواین که پیاده سازی کنن، اگه فیچری مد نظرتون هست باید پیاده سازی کنید، یا نظر سنجی کنید که پول ریکوئستش رو بدید.
