### ISSUE TITLE
مشکل در فیلتر pDigtWords

### ISSUE THREAD

**Issue by masoodtrb** [mohebifar/angular-persian#9]
هنگام استفاده از فيلتر

> pDigitWords

عدد به دست امده به صورت زير است

<img width="412" alt="screen shot 1395-01-31 at 16 19 07" src="https://cloud.githubusercontent.com/assets/9899801/14638548/f24c6eea-064c-11e6-8c9d-0dd1b518826b.png">

**Comment by mohebifar** [comment]
ممنون بابت گزارش مشکل
جالبه که بعد از دو سال هنوز کسی متوجه این موضوع نشده بود.

**Comment by mohebifar** [comment]
باگ برطرف شد به نسخه ۲.۰.۳ آپگرید کنید.

**Comment by masoodtrb** [comment]
@mohebifar 👍 tnx
